# https://www.home-assistant.io/integrations/default_config/
default_config:

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: warning
  logs:
    custom_components.modbus_logo: debug

modbus_logo:
  - name: plc
    type: tcp
    host: 127.0.0.1
    port: 502
    lights:
      - name: test
        address: 1
        write_type: coil

